# Generated by Django 4.2.30 on 2026-06-16 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                (
                    "question_type",
                    models.CharField(
                        choices=[("mcq", "MCQ"), ("text", "Text Answer")],
                        default="mcq",
                        max_length=10,
                    ),
                ),
                ("option_a", models.CharField(blank=True, max_length=255)),
                ("option_b", models.CharField(blank=True, max_length=255)),
                ("option_c", models.CharField(blank=True, max_length=255)),
                ("option_d", models.CharField(blank=True, max_length=255)),
                ("correct_answer", models.TextField()),
                ("marks", models.IntegerField(default=1)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="exams.exam",
                    ),
                ),
            ],
        ),
    ]
